# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: octane-start-task@1
  inputs:
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'AzureExtensionPipelineServiceConnection'
    WorkspaceList: '29001'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: octane-start-task@1
  inputs:
  - task: octane-end-task@2
    inputs:
      OctaneServiceConnection: 'AzureExtensionPipelineServiceConnection'
      WorkspaceList: '29001'